name: movies_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  get_storage: ^2.1.1
  path_provider: ^2.0.15
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.3
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  background_image: 'assets/splash_screen.png'
  android: true
  web: true
  fullscreen: true 
  color: '#594747'



icons_launcher:
  image_path: "assets/launcher_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
